### PR TITLE
Generate Paranthesis

### PR DESCRIPTION
**Pull request by mansimaurya19**
Contributed solution to above problem.

### CODE REVIEW

**Review by dheeraj-2000 — COMMENTED** [review]
hey @mansimaurya19 Please add the problem link in your code file and resend your PR, it'll be easy for everyone to visit the problem.

**Comment by mansimaurya19** [comment]
I have added the link to the problem statement

**Comment by mansimaurya19** [comment]
I have added the problem link now

**Comment by dheeraj-2000** [comment]
@mansimaurya19 you've closed this PR. You don't want to contribute this file?

**Pull request closed without merging**
