### PR TITLE
Simple unidirectional linked list in C

### PR DESCRIPTION
**Pull request by Elismar13**
Simple unidirectional linked list in C with example.

What i have done 🤔: 

- [x] created linkedList with these functions:
> - createList;
> - add;
> - printList;
> - isEmpty;
> - removeBack;
> - size;

- [x] test example;

### CODE REVIEW

**Review by dheeraj-2000 — COMMENTED** [review]
Hey @Elismar13, thanks for your contribution, but there's already a folder of **Linked_list** , in which there're implementations in both C & C++ that do similar tasks as your this file does. 
So, please send a PR with some new program/algorithms, or check that **Linked_list** folder and let me know if your this file is different from them.

**Comment by Elismar13** [comment]
I haven't seen the C implementation before, but now I found it in the folder. 
*Suggestion:* separate C/C++ implementation in sub-folders of *Linked_list*.

In order not to lose my code, I can do more functions like: insert in a specific position, get a specific value, check if there is a value, and more... 
What do you think? Any suggestions?

**Comment by Elismar13** [comment]
I haven't seen the C implementation before, but now I found it in the folder.
**_Suggestion:_** separate C/C++ implementation in sub-folders of **Linked_list**.

In order not to lose my code, I can do more functions like: insert in a specific position, get a specific value, check if there is a value, and more... (that doesn't exists on C implementation)
What do you think? Any suggestions?

**Comment by dheeraj-2000** [comment]
@Elismar13 yes sure I'll keep them in separate folder but after this Hactoberfest, you do your modiifications and resend the PR.

**Comment by Elismar13** [comment]
Hey @ dheeraj-2000, as I promised, here it is!

I made 4 new functions:

- [x] Check if elements exists in a list;
- [x] Insert element in a specific position;
- [x] Remove element in a specific position;
- [x] Get an element address by a specific position;

**Review by dheeraj-2000 — APPROVED** [review]

**Comment by dheeraj-2000** [comment]
Hey @Elismar13 thanks for your contribution, 

Cheers:v:

**Pull request merged**
