### PR TITLE
Snakes and Ladders problem

### PR DESCRIPTION
**Pull request by sanjaydogood**
This is a well commented code for the Snakes and Ladders Problem. This is the solution for the GFG(Geeks for Geeks) Snakes and Ladders Question.

### CODE REVIEW

**Review by dheeraj-2000 — APPROVED** [review]

**Comment by dheeraj-2000** [comment]
@sanjaydogood Thanks for your contribution

**Comment by sanjaydogood** [comment]
Hey @dheeraj-2000 . Could you please merge the changes if everything looks good? Thanks!

**Comment by dheeraj-2000** [comment]
Don't worry @sanjaydogood I've approved and also labelled your files, it'll be counted towards Hacktoberfest :)
Will merge them soon.

Cheers✌️

**Comment by sanjaydogood** [comment]
Thanks! :D

**Pull request merged**
