### PR TITLE
Added some subfolder for different languages

### PR DESCRIPTION
**Pull request by lkbhitesh07**
Just for ease, I have differentiated between the languages so that it'll be easy to find. Planning to add some python file.

### CODE REVIEW

**Comment by lkbhitesh07** [comment]
@dheeraj-2000 If you find it useful please do let me know then I'll commit some more changes. Thanks

**Review by dheeraj-2000 — COMMENTED** [review]
Hey @lkbhitesh07 thanks for your this contribution, I thought you want to add some new files for Interview Preparation.
Right now I'm intentionally not doing this, I know it'll be more helpfull but I'll do this after merging all the approved PRs after this Hactoberfest. As there will be chances of some conflicts as files will be relocated, so it'll become difficult for beginners. 
So to avoid such issues, I'm not relocating any files till hacktoberfest.

And if want to contribute some new Algo/codes you are most welcome, and if you're interested in doing such sorting of files than let me know, I'll inform you the day I merge all PRs and than you can do these changes.

Cheers :v:

**Comment by lkbhitesh07** [comment]
Sure @dheeraj-2000 , we can do that also is there any contribution you would like me to make in this hactoberfest, I know I'm being selfish here but I really want to clear my hactoberfest as no one has approved my PR as far I've made the contribution ,also I'll help you out with all kind of things.

**Comment by dheeraj-2000** [comment]
@lkbhitesh07 yes you can close this for now.
And regarding contribution, you can contribute any problems from Leetcode, or any problems of arrays or anything. Just check the folders already present and contribute to any of them, which you find yourself comfortable.
But make sure to add problem link in your code file if you're adding any problem, and if possible you can add complexity of the code. And keep the code in respective folder.
Also you can write any present code in any other language, but keep the filename similar to the present one (only extension will be changed)

**Pull request closed without merging**
