### PR TITLE
Added dnf-sort by GamerNishant

### PR DESCRIPTION
**Pull request by GamerNishant**
Respected Sir, 

With due respect, I want to mention that I added a dnf-sort.cpp file that has code for dnf-sort, It is very helpful in cases where 3 numbers input stream is provided it is very fast and light weight but is missing from your Sort folder code.

### CODE REVIEW

**Comment by GamerNishant** [comment]
Sir your repository is showing ineligible in hactober fest. Please took this into consideration.

**Comment by GamerNishant** [comment]
Sir Actually, Your repository is not opted - in for hacktober fest reason is that the tag you entered has a typo in it. please correct this  spelling before merging it. 
 current spelling - hactoberfest
correct spelling - hacktoberfest
please add the missing k in it.

**Comment by dheeraj-2000** [comment]
Thanks @GamerNishant for that typo, actually it was added by the suggestion. And I havent checked it's spelling.
Cheers :v:

**Review by dheeraj-2000 — APPROVED** [review]

**Comment by dheeraj-2000** [comment]
@GamerNishant let me know if it's working now or not.

**Pull request merged**
