### PR TITLE
Top 450 Questions and some solutions

### PR DESCRIPTION
**Pull request by lkbhitesh07**
@dheeraj-2000  Please take a look at this, I will be adding more solutions as soon as I'll solve it. Thanks
Do let me know if you want me to change something.
Thanks

### CODE REVIEW

**Review by dheeraj-2000 — COMMENTED** [review]
hey @lkbhitesh07 i need few modification, please convert your file to .py extension. Usually we don't open these codes in jupyter notebook, so it'll be better if you convert your python file to .py extension.

**Comment by lkbhitesh07** [comment]
> hey @lkbhitesh07 i need few modification, please convert your file to .py extension. Usually we don't open these codes in jupyter notebook, so it'll be better if you convert your python file to .py extension.

On it.

**Comment by lkbhitesh07** [comment]
@dheeraj-2000 Please take a look, also would you mind adding label of hactoberfest-accepted to it?
Thanks, do let me know if you need help in anything else.

**Review by dheeraj-2000 — APPROVED** [review]

**Comment by lkbhitesh07** [comment]
Hey, are you willing to merge this PR? Or you need some more changes because I was thinking to make some more changes in other files.

**Comment by dheeraj-2000** [comment]
@lkbhitesh07 Yes I'll merge this PR, but if want to contribute more new files, then you can do

**Comment by lkbhitesh07** [comment]
> @lkbhitesh07 Yes I'll merge this PR, but if want to contribute more new files, then you can do

Sure. Thanks

**Comment by lkbhitesh07** [comment]
Hey, @dheeraj-2000 I have an idea just tell me if you like it or not, We can simply add some youtube videos and some great blogs or interview experiences which can help others in many ways. Do you want me to work on it?

**Comment by dheeraj-2000** [comment]
Thanks for your suggestion @lkbhitesh07, but I'm not doing like that as of now. 
Instead if you are sharing some good algorithm, than at the top of your code file, you can comment out problem link, blogs or video link which explains that code. But make sure to write in a good way.

**Comment by lkbhitesh07** [comment]
> Thanks for your suggestion @lkbhitesh07, but I'm not doing like that as of now.
> Instead if you are sharing some good algorithm, than at the top of your code file, you can comment out problem link, blogs or video link which explains that code. But make sure to write in a good way.

Sure.

**Comment by lkbhitesh07** [comment]
Thanks for merging @dheeraj-2000

**Pull request merged**
