### PR TITLE
added solution to demonstrate STL stack in cpp

### PR DESCRIPTION
**Pull request by saikumar010**

### CODE REVIEW

**Review by dheeraj-2000 — CHANGES_REQUESTED** [review]
@saikumar010 please add your code to some relavant existing folders, don't create new folder. And if this's asked in some interview, then you can write some description of the problem within your file

**Comment by saikumar010** [comment]
I could not find a relevant folder for this, can you suggest where I could put this?

**Comment by dheeraj-2000** [comment]
@saikumar010 you can add to **stack** folder, and it'll be good if you give a brief description of your code.

**Comment by saikumar010** [comment]
Made the requested changes.

**Review by dheeraj-2000 — APPROVED** [review]

**Pull request merged**
